version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'localhost -> http://web:8000'
      STAGE: 'local' # Don't use production until staging works
      # FORCE_RENEW: 'true'
  web:
    image: nginx:1.17-alpine
    ports:
    - 8000:8000
    volumes:
      - ./:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  node:
    image: node:15
    tty: true
    volumes:
      - ./script:/src
    working_dir: "/src"
